// ============================================================
//  DATA.JS — Données statiques du jeu
//  Les Huit Communes ~ Athis-Val-de-Rouvre
// ============================================================

const DATA = {
    MAP_W: 80,
    MAP_H: 60,
    TILE: 32,
    GOAL_VILLAGERS: 100,

    // --- Tiles ---
    TILES: {
        GRASS: 0, TALL_GRASS: 1, FLOWERS: 2, PATH: 3, ROAD: 4,
        WATER: 5, DEEP_WATER: 6, TREE: 7, DENSE_TREE: 8, ROCK: 9,
        FLOOR: 10, WALL: 11, BRIDGE: 12, FENCE: 13,
        GARDEN_SOIL: 14, WHEAT: 15, SAND: 16, BUSH: 17,
        ROOF_RED: 18, ROOF_BLUE: 19, DOOR: 20, SIGN: 21,
        BIKE_PATH: 22, BENCH: 23, WELL: 24, CHAPEL: 25
    },

    WALKABLE: new Set([0, 1, 2, 3, 4, 12, 14, 16, 20, 22, 23]),

    TILE_COLORS: {
        0:  ['#7EC850','#72B847','#84CE58'],
        1:  ['#6AAF3D','#5E9E35','#74BA45'],
        2:  ['#7EC850','#7EC850','#7EC850'],
        3:  ['#D4A574','#C89B6B','#DEAD7E'],
        4:  ['#B8A08A','#A89478','#C2AA94'],
        5:  ['#5B9BD5','#4F8BC5','#67A5DF'],
        6:  ['#3A7BBF','#2E6BAF','#4685C9'],
        7:  ['#7EC850','#7EC850','#7EC850'],
        8:  ['#5DA832','#5DA832','#5DA832'],
        9:  ['#A0A0A0','#909090','#B0B0B0'],
        10: ['#E8D5C0','#DEC8B2','#F2E0CE'],
        11: ['#C4A882','#B89B75','#D0B58F'],
        12: ['#B8956A','#A88560','#C8A574'],
        13: ['#8B6E4E','#7D6345','#996F57'],
        14: ['#8B6B3E','#7D5F35','#997747'],
        15: ['#E8D060','#DCC450','#F0DC6A'],
        16: ['#E8D5A0','#DEC990','#F2DFB0'],
        17: ['#5DA832','#5DA832','#5DA832'],
        18: ['#C65D3E','#B85235','#D06847'],
        19: ['#4A6FA5','#3F6298','#557CB2'],
        20: ['#8B6E4E','#7D6345','#996F57'],
        21: ['#D4A574','#D4A574','#D4A574'],
        22: ['#A0C8A0','#90B890','#B0D8B0'],
        23: ['#8B6E4E','#8B6E4E','#8B6E4E'],
        24: ['#909090','#909090','#909090'],
        25: ['#D0C0A0','#D0C0A0','#D0C0A0'],
    },

    // --- Les 8 vraies communes ---
    COMMUNES: {
        'athis': {
            name: 'Athis-de-l\'Orne',
            cx: 40, cy: 32,
            desc: 'Le bourg principal, coeur vivant de la communaute.',
            terrain: 'village',
            color: '#E8C850'
        },
        'ronfeugerai': {
            name: 'Ronfeugerai',
            cx: 40, cy: 8,
            desc: 'Un hameau tranquille au bord de la riviere.',
            terrain: 'valley',
            color: '#5B9BD5'
        },
        'carneille': {
            name: 'La Carneille',
            cx: 14, cy: 10,
            desc: 'Forets profondes et collines boisees.',
            terrain: 'forest',
            color: '#2D7A2D'
        },
        'taillebois': {
            name: 'Taillebois',
            cx: 8, cy: 38,
            desc: 'Au coeur de la foret, un havre de paix pour la faune.',
            terrain: 'deep_forest',
            color: '#1B5E1B'
        },
        'segrie': {
            name: 'Segrie-Fontaine',
            cx: 20, cy: 52,
            desc: 'Celebre pour ses sources et ses prairies fleuries.',
            terrain: 'meadow',
            color: '#FF88AA'
        },
        'breel': {
            name: 'Breel',
            cx: 65, cy: 12,
            desc: 'De vastes champs dores et des fermes accueillantes.',
            terrain: 'farmland',
            color: '#E8D060'
        },
        'tourailles': {
            name: 'Les Tourailles',
            cx: 72, cy: 35,
            desc: 'Un plateau venteux avec un panorama splendide.',
            terrain: 'highland',
            color: '#A0A0A0'
        },
        'ndrocher': {
            name: 'Notre-Dame-du-Rocher',
            cx: 58, cy: 50,
            desc: 'Rochers imposants et une chapelle historique.',
            terrain: 'rocky',
            color: '#B0A090'
        }
    },

    // --- Crops (waterPerStage = arrosages necessaires par stade) ---
    CROPS: {
        tomate:    { name: 'Tomates',         icon: '#FF4444', growTime: 4, season: ['ete'],             waterPerStage: 2, sellValue: 3 },
        carotte:   { name: 'Carottes',         icon: '#FF8800', growTime: 3, season: ['printemps','ete'], waterPerStage: 1, sellValue: 2 },
        salade:    { name: 'Salades',          icon: '#88DD44', growTime: 2, season: ['printemps'],       waterPerStage: 1, sellValue: 2 },
        courgette: { name: 'Courgettes',       icon: '#44AA22', growTime: 4, season: ['ete'],             waterPerStage: 2, sellValue: 3 },
        patate:    { name: 'Pommes de terre',  icon: '#C8A060', growTime: 5, season: ['printemps','ete'], waterPerStage: 1, sellValue: 4 },
        fraise:    { name: 'Fraises',          icon: '#FF3366', growTime: 3, season: ['printemps','ete'], waterPerStage: 2, sellValue: 5 },
        tournesol: { name: 'Tournesols',       icon: '#FFD700', growTime: 5, season: ['ete'],             waterPerStage: 2, sellValue: 6 },
        citrouille:{ name: 'Citrouilles',      icon: '#FF6600', growTime: 6, season: ['automne'],         waterPerStage: 2, sellValue: 7 },
    },

    CROP_STAGES: ['vide', 'seme', 'pousse', 'grandit', 'floraison', 'pret'],

    // --- Buildings : tier=1 always available, tier 2-4 need requirements ---
    // requires.happiness, requires.buildings, requires.built_one_of (array of building type keys)
    BUILDINGS: {
        // ── Tier 1 : toujours disponibles ───────────────────────────────
        bench:      { tier:1, requires:{},
                      name: 'Banc public',       cost: {bois:2},           happiness: 1,
                      desc: 'Pour se reposer et admirer le paysage.' },
        flowerbed:  { tier:1, requires:{},
                      name: 'Massif fleuri',     cost: {bois:1},           happiness: 2,
                      desc: 'Des couleurs pour égayer le village.' },
        bike_path:  { tier:1, requires:{},
                      name: 'Piste cyclable',    cost: {bois:3, pierre:2}, happiness: 3,
                      desc: 'Un chemin vert pour les vélos !' },
        // ── Tier 2 : 1 bâtiment construit ───────────────────────────────
        garden:     { tier:2, requires:{buildings:1},
                      name: 'Jardin partagé',    cost: {bois:2, pierre:1}, happiness: 2,
                      desc: 'Un espace fleuri pour tous.' },
        duck_pond:  { tier:2, requires:{buildings:1},
                      name: 'Mare aux canards',  cost: {pierre:3},         happiness: 3,
                      desc: 'Coin-coin ! Attire la faune.' },
        chaumiere:  { tier:2, requires:{buildings:1},
                      name: 'Chaumière',         cost: {bois:3},           happiness: 3,
                      desc: 'Un toit de chaume douillet pour une famille.', attractsVillagers: 1 },
        lavoir:     { tier:2, requires:{buildings:1},
                      name: 'Lavoir',            cost: {pierre:2, bois:1}, happiness: 2,
                      desc: 'Un lavoir au bord de l\'eau, lieu de bavardage.' },
        // ── Tier 3 : 3 bâtiments + prérequis spécifiques ──────────────
        bakery:     { tier:3, requires:{buildings:3, built_one_of:['garden','chaumiere']},
                      name: 'Boulangerie',       cost: {bois:4, pierre:4}, happiness: 5,
                      desc: 'Du bon pain frais chaque matin !',
                      produces: {bois:1}, produceTurns: 12 },
        library:    { tier:3, requires:{buildings:3, happiness:18},
                      name: 'Bibliothèque',      cost: {bois:4, pierre:3}, happiness: 4,
                      desc: 'Le savoir à portée de tous.',
                      produces: {pierre:1}, produceTurns: 12 },
        maison:     { tier:3, requires:{buildings:3, built_one_of:['chaumiere']},
                      name: 'Maison normande',   cost: {bois:5, pierre:3}, happiness: 4,
                      desc: 'Colombages et pommiers, une vraie maison de pays.', attractsVillagers: 2 },
        gite:       { tier:3, requires:{buildings:3, happiness:15},
                      name: 'Gîte rural',        cost: {bois:4, pierre:4}, happiness: 4,
                      desc: 'Accueille des visiteurs et rayonne sur la région.',
                      produces: {bois:1}, produceTurns: 10, attractsVillagers: 1 },
        atelier:    { tier:3, requires:{buildings:3, built_one_of:['bakery','lavoir']},
                      name: 'Atelier',           cost: {bois:4, pierre:3}, happiness: 4,
                      desc: 'Un atelier pour les artisans du village.',
                      produces: {pierre:1}, produceTurns: 10 },
        marche:     { tier:3, requires:{buildings:3, built_one_of:['gite','chaumiere']},
                      name: 'Marché couvert',    cost: {bois:5, pierre:2}, happiness: 5,
                      desc: 'Un marché pour les produits du terroir normand.',
                      produces: {bois:1, pierre:1}, produceTurns: 12 },
        // ── Tier 4 : 5 bâtiments + prérequis avancés ───────────────────
        fountain:   { tier:4, requires:{buildings:5, happiness:25},
                      name: 'Fontaine',          cost: {pierre:5},         happiness: 4,
                      desc: 'Un point d\'eau rafraîchissant.',
                      produces: {pierre:1}, produceTurns: 15 },
        guesthouse: { tier:4, requires:{buildings:5, built_one_of:['maison','gite']},
                      name: 'Maison d\'hôtes',   cost: {bois:5, pierre:5}, happiness: 4,
                      desc: 'Accueille de nouveaux habitants.',
                      produces: {bois:1, pierre:1}, produceTurns: 15, attractsVillagers: 2 },
        windmill:   { tier:4, requires:{buildings:5, built_one_of:['bakery']},
                      name: 'Moulin',            cost: {bois:6, pierre:4}, happiness: 5,
                      desc: 'Transforme le blé en farine, symbole du plateau.',
                      produces: {bois:2}, produceTurns: 15 },
        ferme:      { tier:4, requires:{buildings:5, built_one_of:['maison','gite']},
                      name: 'Ferme rénovée',     cost: {bois:6, pierre:5}, happiness: 5,
                      desc: 'Une belle ferme normande au cœur du village.',
                      produces: {bois:2, pierre:1}, produceTurns: 12, attractsVillagers: 3 },
        ecole:      { tier:4, requires:{buildings:5, built_one_of:['library','maison']},
                      name: 'École',             cost: {bois:6, pierre:4}, happiness: 6,
                      desc: 'Une école pour les enfants du village.',
                      produces: {pierre:1}, produceTurns: 15, attractsVillagers: 3 },
        pressoir:   { tier:4, requires:{buildings:5, built_one_of:['ferme','windmill']},
                      name: 'Pressoir à cidre',  cost: {bois:5, pierre:5}, happiness: 5,
                      desc: 'Un pressoir à cidre, spécialité normande !',
                      produces: {bois:2, pierre:1}, produceTurns: 12 },
    },

    // --- Items ---
    ITEMS: {
        bois:       { name: 'Bois',         icon: '#8B6E4E', desc: 'Du bois de construction.' },
        pierre:     { name: 'Pierre',       icon: '#909090', desc: 'De la bonne pierre solide.' },
        graine_t:   { name: 'Graines tomate',    icon: '#FF4444', crop: 'tomate' },
        graine_c:   { name: 'Graines carotte',   icon: '#FF8800', crop: 'carotte' },
        graine_s:   { name: 'Graines salade',    icon: '#88DD44', crop: 'salade' },
        graine_co:  { name: 'Graines courgette', icon: '#44AA22', crop: 'courgette' },
        graine_p:   { name: 'Graines patate',    icon: '#C8A060', crop: 'patate' },
        graine_f:   { name: 'Graines fraise',    icon: '#FF3366', crop: 'fraise' },
        graine_to:  { name: 'Graines tournesol', icon: '#FFD700', crop: 'tournesol' },
        graine_ci:  { name: 'Graines citrouille',icon: '#FF6600', crop: 'citrouille' },
        fleur:      { name: 'Fleurs',       icon: '#FF88AA', desc: 'Un joli bouquet.' },
        champignon: { name: 'Champignons',  icon: '#C4A060', desc: 'Des champignons forestiers.' },
        poisson:    { name: 'Poisson',      icon: '#5B9BD5', desc: 'Un beau poisson.' },
        miel:       { name: 'Miel',         icon: '#FFB347', desc: 'Du miel dore et sucre.' },
        pomme:      { name: 'Pommes',       icon: '#FF4444', desc: 'De belles pommes normandes.' },
        herbes:     { name: 'Herbes',       icon: '#66BB66', desc: 'Des herbes aromatiques.' },
    },

    // --- NPCs ---
    NPCS: [
        { id:'maire', name:'Marcel le Maire', commune:'athis', rx:2, ry:0, color:'#4A6FA5', hair:'#808080',
          personality: 'Bienveillant et passionné par son village',
          friends: ['meunier'],
          friend_quips: [
              'Augustin m\'a dit que vous étiez passé aux Tourailles ! La vue, n\'est-ce pas ?',
              'Le meunier et moi, on se connaît depuis l\'enfance. De bons vieux amis.',
          ],
          dialogue: [
              'Bienvenue à Athis-Val-de-Rouvre !',
              'Notre rêve : attirer 100 habitants dans nos huit communes.',
              'Voici des graines et des matériaux pour bien démarrer.',
              'Explorez, cultivez, construisez... les gens viendront !',
              'Parlez aux habitants, ils échangent des récoltes contre des matériaux.',
          ],
          quips: [
              'Le village grandit à vue d\'oeil, grâce à vous!',
              'J\'ai vu de nouvelles familles s\'installer cette semaine.',
              'Les habitants parlent de vous en bien, vous savez.',
              'Un bon maire, c\'est un maire qui écoute. Et là, j\'entends des choses superbes!',
          ],
          seasonal: {
              printemps: 'Le printemps est là — c\'est le meilleur moment pour planter!',
              ete: 'Cette chaleur est bonne pour les récoltes. Profitez-en!',
              automne: 'L\'automne dore les collines de Normandie... magnifique.',
              hiver: 'Brr! Un hiver rude, mais notre village tient bon. Comme toujours.',
          },
          gives: { graine_t:3, graine_c:3, graine_s:3, graine_p:2, bois:8, pierre:5 },
          quest: 'welcome'
        },
        { id:'fermiere', name:'Josette la Fermière', commune:'breel', rx:-1, ry:1, color:'#DD6644', hair:'#C8A060',
          friends: ['apiculteur'],
          friend_quips: [
              'Paul m\'a apporté du miel pour ma confiture de tomates. Maintenant elle est parfaite !',
              'L\'apiculteur et moi on s\'entraide : ses abeilles pollinisent mes champs, je lui donne des fraises.',
          ],
          personality: 'Chaleureuse, fière de ses récoltes, un peu compétitive',
          dialogue: [
              'Bonjour! Les champs de Breel sont les plus beaux de Normandie!',
              'Vous connaissez les tomates? Les miennes sont légendaires dans la région.',
              'Ramenez-moi de belles tomates et je vous confierai mes graines secrètes!',
          ],
          quips: [
              'Ce matin j\'ai fait une confiture de tomates... un régal!',
              'Mon potager et le vôtre, on devrait s\'échanger des graines plus souvent.',
              'La terre de Breel est riche. On est chanceux d\'être ici.',
              'J\'ai un secret pour des tomates sucrées — mais chut, c\'est entre nous!',
              'Vous avez vu mes tournesols? Ils atteignent presque deux mètres cette année!',
          ],
          seasonal: {
              printemps: 'Je plante mes premières tomates dès que le sol est chaud. La patience, c\'est la clé!',
              ete: 'C\'est la haute saison! Mes champs débordent. Je ne sais plus où donner de la tête.',
              automne: 'L\'automne c\'est les citrouilles et les confitures. Le meilleur moment de l\'année!',
              hiver: 'En hiver je range mes graines et je prépare mes plans de culture. Jamais de repos!',
          },
          gives: { graine_co:3, graine_to:2 },
          friendship_gift: { bois:3, graine_t:4 },
          quest: 'fermiere',
          trade: { want:'tomate', wantQty:2, give:'graine_co', giveQty:2, give2:'graine_ci', giveQty2:1,
                   msg:'Mmh, belles tomates! Exactement ce qu\'il me fallait. Voici mes meilleures graines!' }
        },
        { id:'bucheron', name:'Henri le Bûcheron', commune:'carneille', rx:1, ry:1, color:'#AA4444', hair:'#4A2810',
          friends: ['garde'],
          friend_quips: [
              'Sylvie et moi, on fait le tour de la forêt chaque dimanche. Comme tradition.',
              'La garde m\'a appris à écouter la forêt. Depuis, je ne la coupe plus, je la soigne.',
          ],
          personality: 'Taciturne mais loyal, parle peu mais fait confiance lentement',
          dialogue: [
              '...',
              'La forêt de La Carneille. C\'est mon domaine.',
              'Pas de bruit inutile ici. Les arbres ont besoin de calme.',
              'Vous cherchez quelque chose? Des patates contre du bois, ça me convient.',
          ],
          quips: [
              '...Vous revenez. Bien.',
              'Le vieux chêne là-bas a mille ans. Il a vu bien des choses.',
              'Je coupe seulement les arbres malades. Les autres, je les laisse vivre.',
              'Hier j\'ai vu un cerf blanc. Ça porte bonheur, paraît-il.',
              'Merci pour les patates. Je ne le dis pas souvent, mais... merci.',
          ],
          seasonal: {
              printemps: 'La forêt reverdit. C\'est le moment que je préfère. On se tait et on écoute.',
              ete: 'Trop chaud pour abattre des arbres. Je taille les branches mortes, c\'est tout.',
              automne: 'L\'automne c\'est la saison des champignons. Je connais les bons coins.',
              hiver: 'Le froid conserve le bois. C\'est ma saison de travail préférée.',
          },
          gives: { bois:5 },
          friendship_gift: { champignon:3, bois:6 },
          quest: 'bucheron',
          trade: { want:'patate', wantQty:2, give:'bois', giveQty:4,
                   msg:'Des patates. Bien. Voilà du bois en échange. Du bon.' }
        },
        { id:'herboriste', name:'Madeleine l\'Herboriste', commune:'segrie', rx:-1, ry:-1, color:'#88AA44', hair:'#AA6633',
          friends: ['soeur'],
          friend_quips: [
              'Sœur Thérèse m\'a confié sa recette de tisane de lavande. C\'est magique.',
              'La sœur et moi, on échange des herbes contre des prières. Un marché équitable !',
          ],
          personality: 'Mystérieuse et sage, parle des plantes comme de vieilles amies',
          dialogue: [
              'Vous sentez? Ces herbes... chaque arôme raconte une histoire.',
              'Les sources de Ségrie-Fontaine ont des vertus extraordinaires.',
              'Je soigne avec des plantes depuis quarante ans. Ma grand-mère m\'a tout appris.',
              'Ramenez-moi des carottes fraîches — je vous donnerai mes meilleures tisanes.',
          ],
          quips: [
              'Cette lavande que j\'ai plantée il y a vingt ans fleurit encore. Fidèle.',
              'Les plantes savent quand on les aime. Elles poussent mieux, vous verrez.',
              'J\'ai préparé une tisane pour vous... mais la prochaine fois, vous me ramenez des carottes!',
              'Chaque saison amène ses plantes. Et ses secrets.',
              'Vous avez les mains qui sentent la terre. C\'est bon signe.',
          ],
          seasonal: {
              printemps: 'Au printemps les herbes ont leurs meilleures vertus. Je récolte à l\'aube, sous la rosée.',
              ete: 'Attention à la chaleur — les herbes sèchent vite. Je les protège avec de l\'ombre et de l\'eau.',
              automne: 'L\'automne c\'est les racines. Elles gardent toute leur force pour l\'hiver.',
              hiver: 'En hiver je fais sécher mes herbes et je prépare mes onguents. La maison sent bon.',
          },
          gives: { herbes:3, graine_f:3 },
          friendship_gift: { herbes:4, graine_f:2, graine_to:2 },
          quest: 'herboriste',
          trade: { want:'carotte', wantQty:3, give:'herbes', giveQty:2, give2:'graine_f', giveQty2:1,
                   msg:'Des carottes fraîches, comme je les aime! Tenez — herbes rares et graines de fraises.' }
        },
        { id:'pecheur', name:'Robert le Pêcheur', commune:'ronfeugerai', rx:1, ry:2, color:'#5588AA', hair:'#444444',
          friends: ['bucheron'],
          friend_quips: [
              'J\'ai dit à Henri qu\'il devrait venir pêcher. Il a besoin de calme, ce bûcheron.',
              'Henri m\'apporte parfois du bois pour réparer mes nasses. Un brave homme.',
          ],
          personality: 'Philosophe et tranquille, la rivière est sa maison',
          dialogue: [
              'Bonjour! Vous arrivez au bon moment — j\'ai pêché une belle truite ce matin.',
              'La rivière de Ronfeugerai... elle coule depuis toujours et coulera encore longtemps.',
              'La pêche, ça apprend la patience. Et la patience, ça change une vie.',
              'Apportez-moi du miel et je partage ma prise du jour avec vous!',
          ],
          quips: [
              'Ce matin l\'eau était si claire... j\'ai vu le fond.',
              'Un pêcheur qui se dépêche ne prend jamais rien. Souvenez-vous-en.',
              'Il y a un héron qui vient me voir tous les matins. Je lui laisse quelques poissons.',
              'La rivière chante différemment selon les saisons. Vous avez l\'oreille pour ça?',
              'Mon père, et son père, ont pêché ici. C\'est une tradition.',
          ],
          seasonal: {
              printemps: 'Au printemps les truites remontent la rivière. C\'est spectaculaire!',
              ete: 'Je pêche tôt le matin, avant la chaleur. À l\'ombre des saules.',
              automne: 'Les feuilles tombent dans l\'eau. J\'aime regarder ça.',
              hiver: 'La pêche sous la glace... ça paraît fou, mais les truites d\'hiver sont les meilleures.',
          },
          gives: { poisson:2, bois:2 },
          friendship_gift: { poisson:4, herbes:2 },
          quest: 'pecheur',
          trade: { want:'miel', wantQty:1, give:'poisson', giveQty:3,
                   msg:'Du miel doré! Mes truites vont adorer ça comme appât. Voici ma prise du jour!' }
        },
        { id:'garde', name:'Sylvie la Garde', commune:'taillebois', rx:0, ry:1, color:'#557744', hair:'#884422',
          friends: ['bucheron'],
          friend_quips: [
              'Henri et moi, on surveille ensemble les frontières de la forêt. On se comprend sans mots.',
              'Le bûcheron m\'a offert une sculpture en bois... un héron. Il est doué, ce grand taciturne.',
          ],
          personality: 'Passionnée de nature, parle doucement pour ne pas effrayer les animaux',
          dialogue: [
              'Chut... regardez là-bas. Un cerf avec ses faons!',
              'Taillebois est un sanctuaire. Chaque animal y a sa place.',
              'J\'ai choisi ce métier parce que la forêt m\'a choisie d\'abord, je crois.',
              'Vous avez des champignons? Je vous échange du bois mort ramassé à la main.',
          ],
          quips: [
              'Ce matin j\'ai compté sept espèces d\'oiseaux. Record de la saison!',
              'Le renard a eu des petits! Je les vois de ma cabane chaque soir.',
              'On a réintroduit les hérissons l\'an dernier. Ils s\'adaptent bien.',
              'Jamais de bruit fort ici. Les animaux ont besoin de silence pour vivre.',
              'Vous observez beaucoup la nature? Ça se voit dans vos yeux.',
          ],
          seasonal: {
              printemps: 'Les naissances commencent! Faons, lapereaux, oisillons... c\'est un émerveillement chaque année.',
              ete: 'Les animaux cherchent l\'ombre et l\'eau. Je leur installe des points d\'eau frais.',
              automne: 'La migration commence. Les martinets partent pour l\'Afrique. Bon voyage!',
              hiver: 'En hiver je laisse de la nourriture pour les animaux. Personne ne doit souffrir du froid.',
          },
          quest: 'garde',
          gives: { bois:3 },
          friendship_gift: { bois:5, champignon:2 },
          trade: { want:'champignon', wantQty:2, give:'bois', giveQty:3,
                   msg:'Merci pour les champignons! En échange, voici du beau bois mort — bon pour construire.' }
        },
        { id:'meunier', name:'Augustin le Meunier', commune:'tourailles', rx:3, ry:-3, color:'#887766', hair:'#DDCC99',
          friends: ['maire'],
          friend_quips: [
              'Marcel m\'a écrit pour se plaindre du vent... mais le vent fait tourner mon moulin !',
              'Le maire et moi on se téléphone chaque dimanche soir. On parle du village, du temps, de tout.',
          ],
          personality: 'Bavard et généreux, adore le panorama depuis les Tourailles',
          dialogue: [
              'Ah, un visiteur! Venez, venez — la vue d\'ici vaut le déplacement!',
              'Des Tourailles, on voit les huit communes par temps clair. Tous mes voisins!',
              'Mon moulin tourne depuis deux siècles. Il a vu des choses, ce vieux moulin.',
              'Ramenez-moi des salades bien croquantes et je vous donne de la belle pierre!',
          ],
          quips: [
              'Ce matin j\'ai vu les toits de Breel briller dans le soleil levant. Magnifique!',
              'Mon moulin broie le grain du pays entier. C\'est une responsabilité, ça!',
              'Vous savez, de là-haut on voit les orages arriver des heures à l\'avance.',
              'Je fais aussi du cidre! Vous reviendrez à l\'automne, je vous en garde un pot.',
              'Le vent ici est constant. C\'est pour ça que le moulin ne s\'arrête jamais.',
          ],
          seasonal: {
              printemps: 'Le vent de printemps fait tourner le moulin comme jamais! Bonne farine en vue.',
              ete: 'La moisson approche. C\'est ma période la plus chargée. Mais j\'aime ça!',
              automne: 'Les céréales arrivent du pays entier. Je travaille jour et nuit, mais de bon cœur.',
              hiver: 'Le moulin se repose un peu. J\'en profite pour l\'entretenir et regarder le paysage enneigé.',
          },
          gives: { graine_ci:2, pierre:3 },
          friendship_gift: { pierre:5, graine_ci:3 },
          quest: 'meunier',
          trade: { want:'salade', wantQty:2, give:'pierre', giveQty:3,
                   msg:'Des salades fraîches! Parfait pour le déjeuner sur les hauteurs. Voici de la belle pierre.' }
        },
        { id:'soeur', name:'Sœur Thérèse', commune:'ndrocher', rx:0, ry:-1, color:'#555555', hair:'#FFFFFF',
          friends: ['herboriste'],
          friend_quips: [
              'Madeleine m\'apporte des herbes fraîches chaque semaine. C\'est une âme généreuse.',
              'L\'herboriste et moi, on partage la même conviction : la nature guérit.',
          ],
          personality: 'Sereine et bienveillante, trouve le bien dans chaque personne',
          dialogue: [
              'Bonjour, ami. La paix soit avec vous.',
              'La chapelle de Notre-Dame veille sur la vallée depuis des siècles.',
              'Je prie chaque matin pour les habitants de nos huit communes.',
              'Si vous avez des citrouilles à donner, je les échange volontiers contre de la pierre.',
          ],
          quips: [
              'J\'ai réparé le vitrail ce matin. La lumière traverse à nouveau les couleurs.',
              'Les pèlerins viennent de loin pour voir notre chapelle. Chaque visite est une joie.',
              'J\'ai fait de la soupe ce midi avec les légumes du jardin. Simple et bon.',
              'La cloche sonne midi depuis cent ans. Elle ne s\'arrêtera pas.',
              'Peu importe la saison, la porte de la chapelle est toujours ouverte.',
          ],
          seasonal: {
              printemps: 'Le printemps est la résurrection de la nature. Je plante des fleurs autour de la chapelle.',
              ete: 'L\'été je cueille les herbes pour les tisanes des malades du village.',
              automne: 'L\'automne nous rappelle que tout passe. Mais la bonté, elle, reste.',
              hiver: 'L\'hiver je chauffe la chapelle pour les voyageurs qui passent dans le froid.',
          },
          gives: { pierre:5 },
          friendship_gift: { pierre:6, herbes:3 },
          quest: 'soeur',
          trade: { want:'citrouille', wantQty:1, give:'pierre', giveQty:4,
                   msg:'Une citrouille pour la soupe d\'hiver! Que Dieu vous bénisse. Voici de belles pierres.' }
        },
        { id:'apiculteur', name:'Paul l\'Apiculteur', commune:'athis', rx:-4, ry:3, color:'#DDAA33', hair:'#664422',
          friends: ['fermiere'],
          friend_quips: [
              'Josette plante des fleurs pour mes abeilles. Je lui apporte du miel. Un bel échange.',
              'La fermière et moi, on est voisins de cœur. La ferme et les ruches se complètent.',
          ],
          personality: 'Enthousiaste et fier de ses abeilles, les traite comme des amies',
          dialogue: [
              'Bonjour! Approchez, n\'ayez pas peur des abeilles — elles sentent les bonnes intentions!',
              'Mes abeilles produisent le meilleur miel de toute la Normandie.',
              'Chaque ruche a sa personnalité, vous savez. Celle-là est un peu capricieuse...',
              'Ramenez-moi des fraises et je vous donne bois et pierre — un bon marché, non?',
          ],
          quips: [
              'Ce matin mes abeilles étaient de bonne humeur. Signe de beau temps!',
              'J\'ai trente ruches. Trente familles dont je suis responsable. C\'est une fierté.',
              'Le miel de tilleul cette année est exceptionnel — floral, délicat, parfait.',
              'Quand les abeilles dansent en cercle, c\'est qu\'elles ont trouvé des fleurs rares.',
              'Mes abeilles reconnaissent les gens sympas. Elles ne vous ont pas piqué, hein?',
          ],
          seasonal: {
              printemps: 'Les fleurs reviennent, mes abeilles sont folles de joie! La production va être superbe.',
              ete: 'C\'est la grande saison du miel! Je récolte deux fois par semaine.',
              automne: 'Je prépare les ruches pour l\'hiver — bonne isolation, bon stock de miel.',
              hiver: 'Mes abeilles dorment en grappe pour se tenir chaud. Je veille sur elles chaque jour.',
          },
          gives: { miel:3 },
          friendship_gift: { miel:4, graine_f:3 },
          quest: 'apiculteur',
          unlocks: ['apiculteur2'],
          trade: { want:'fraise', wantQty:2, give:'bois', giveQty:2, give2:'pierre', giveQty2:2,
                   msg:'Des fraises! Mes abeilles vont butiner leur parfum toute la journée. Tenez, bois et pierre!' }
        },
    ],

    // --- Wildlife ---
    // domestic:true → ne fuit pas, s'observe avec Espace
    WILDLIFE: {
        cerf:      { name: 'Cerf',           color: '#AA7744', size: 1.2, speed: 0.3, communes: ['taillebois','carneille'] },
        biche:     { name: 'Biche',          color: '#BB8855', size: 1.0, speed: 0.3, communes: ['taillebois','carneille','segrie'] },
        lapin:     { name: 'Lapin',          color: '#C8B090', size: 0.5, speed: 0.6, communes: ['all'] },
        ecureuil:  { name: 'Écureuil',       color: '#CC6633', size: 0.4, speed: 0.7, communes: ['carneille','taillebois','athis'] },
        renard:    { name: 'Renard',         color: '#DD6622', size: 0.8, speed: 0.4, communes: ['taillebois','carneille','breel'] },
        herisson:  { name: 'Hérisson',       color: '#887755', size: 0.4, speed: 0.2, communes: ['all'] },
        canard:    { name: 'Canard',         color: '#338844', size: 0.5, speed: 0.3, communes: ['ronfeugerai','athis'] },
        papillon:  { name: 'Papillon',       color: '#FF88CC', size: 0.3, speed: 0.8, communes: ['segrie','breel','athis'] },
        chouette:  { name: 'Chouette',       color: '#998877', size: 0.6, speed: 0.2, communes: ['taillebois','ndrocher'] },
        martin:    { name: 'Martin-pêcheur', color: '#2288CC', size: 0.4, speed: 0.7, communes: ['ronfeugerai','athis'] },
        pie:       { name: 'Pie',            color: '#222222', size: 0.35, speed: 0.9, communes: ['athis','breel','ronfeugerai'] },
        corneille: { name: 'Corneille',      color: '#111111', size: 0.45, speed: 0.6, communes: ['carneille','ndrocher'] },
        blaireau:  { name: 'Blaireau',       color: '#555544', size: 0.7, speed: 0.25, communes: ['taillebois','carneille','segrie'] },
        salamandre:{ name: 'Salamandre',     color: '#222222', size: 0.3, speed: 0.15, communes: ['segrie','ronfeugerai','ndrocher'] },
        heron:     { name: 'Héron cendré',   color: '#99AABB', size: 1.1, speed: 0.2,  communes: ['ronfeugerai','athis'] },
        // Animaux domestiques – domestic:true → ne fuit pas, observation manuelle
        poule:     { name: 'Poule',          color: '#CC8844', size: 0.4, speed: 0.25, communes: ['breel','athis'], domestic: true },
        vache:     { name: 'Vache',          color: '#DDBBA8', size: 1.5, speed: 0.1,  communes: ['breel','segrie'], domestic: true },
        mouton:    { name: 'Mouton',         color: '#EEEEDD', size: 0.8, speed: 0.2,  communes: ['segrie','tourailles'], domestic: true },
        chevre:    { name: 'Chèvre',         color: '#BBAA88', size: 0.7, speed: 0.3,  communes: ['ndrocher','tourailles'], domestic: true },
    },

    // --- Quests ---
    QUESTS: [
        { id:'welcome', name:'Bienvenue à Athis !',
          desc:'Parler au maire pour découvrir la région.',
          type:'talk', target:'maire',
          reward:{happiness:2},
          rewardText:'Le maire vous a équipé pour démarrer !' },
        { id:'first_harvest', name:'Première Récolte',
          desc:'Faire pousser et récolter votre premier légume.',
          type:'harvest', target:1,
          reward:{happiness:3, items:{graine_p:2}},
          rewardText:'Quel bonheur de manger ses propres légumes !' },
        { id:'explorer', name:'Le Sentier des Huit Communes',
          desc:'Visiter les huit communes d\'Athis-Val-de-Rouvre.',
          type:'visit_all',
          reward:{happiness:10, items:{graine_to:3, graine_ci:3}},
          rewardText:'Vous connaissez maintenant tout le pays !' },
        { id:'piste_verte', name:'La Piste Verte',
          desc:'Construire votre première piste cyclable.',
          type:'build', target:'bike_path',
          reward:{happiness:5},
          rewardText:'Les cyclistes arrivent déjà !' },
        { id:'potager_bonheur', name:'Le Potager du Bonheur',
          desc:'Récolter 5 types de légumes différents.',
          type:'harvest_types', target:5,
          reward:{happiness:8, items:{bois:5, pierre:5}},
          rewardText:'Votre potager est magnifique !' },
        { id:'observation', name:'Observateur de la Nature',
          desc:'Observer 5 espèces animales différentes.',
          type:'observe', target:5,
          reward:{happiness:5},
          rewardText:'La faune vous fait confiance maintenant !' },
        { id:'batisseur', name:'Le Grand Bâtisseur',
          desc:'Construire 5 structures dans le village.',
          type:'build_count', target:5,
          reward:{happiness:10, villagers:2},
          rewardText:'Le village prend forme ! De nouveaux habitants arrivent !' },
        { id:'village_fleuri', name:'Village Fleuri',
          desc:'Atteindre 30 points de bonheur.',
          type:'happiness', target:30,
          reward:{villagers:3},
          rewardText:'Athis-Val-de-Rouvre est devenu un village fleuri !' },
        { id:'fermiere', name:'Les Champs de Breel',
          desc:'Visiter Josette à Breel.',
          type:'talk', target:'fermiere',
          unlocks:['fermiere2'],
          reward:{happiness:2},
          rewardText:'Josette vous a offert des graines rares !' },
        { id:'bucheron', name:'Le Bois de La Carneille',
          desc:'Rencontrer Henri dans la forêt.',
          type:'talk', target:'bucheron',
          unlocks:['bucheron2'],
          reward:{happiness:2},
          rewardText:'Henri est un bon ami à avoir !' },
        { id:'herboriste', name:'Les Sources de Ségrie',
          desc:'Trouver Madeleine près des sources.',
          type:'talk', target:'herboriste',
          unlocks:['herboriste2'],
          reward:{happiness:2},
          rewardText:'Les herbes de Madeleine sentent merveilleusement bon !' },
        { id:'pecheur', name:'Pêche à Ronfeugerai',
          desc:'Aller pêcher avec Robert.',
          type:'talk', target:'pecheur',
          unlocks:['pecheur2'],
          reward:{happiness:2},
          rewardText:'Robert est un pêcheur hors pair !' },
        { id:'garde', name:'Le Sanctuaire de Taillebois',
          desc:'Rencontrer Sylvie la garde forestière.',
          type:'talk', target:'garde',
          unlocks:['garde2'],
          reward:{happiness:2},
          rewardText:'Taillebois recèle des trésors de biodiversité !' },
        { id:'meunier', name:'Le Plateau des Tourailles',
          desc:'Monter voir Augustin aux Tourailles.',
          type:'talk', target:'meunier',
          unlocks:['meunier2'],
          reward:{happiness:2},
          rewardText:'Quel panorama !' },
        { id:'soeur', name:'La Chapelle du Rocher',
          desc:'Visiter Sœur Thérèse à la chapelle.',
          type:'talk', target:'soeur',
          unlocks:['soeur2'],
          reward:{happiness:2},
          rewardText:'Un lieu plein de sérénité.' },
        { id:'apiculteur', name:'Les Ruches d\'Athis',
          desc:'Rencontrer Paul l\'apiculteur près du village.',
          type:'talk', target:'apiculteur',
          unlocks:['apiculteur2'],
          reward:{happiness:2},
          rewardText:'Le miel de Paul est le plus doux de Normandie !' },
        // --- Quêtes secondaires (débloquées par les primaires) ---
        // deliver = livrer un item à un PNJ, trade_count = faire N échanges, build_type = construire un type
        // friendship = atteindre un niveau d'amitié, talk/observe = existants
        { id:'fermiere2', name:'La Confiture de Josette',
          desc:'Josette rêve d\'une confiture au miel. Apportez-lui 2 pots de miel.',
          type:'deliver', target:'fermiere', item:'miel', qty:2,
          locked:true,
          deliverMsg:'Du miel ! Exactement ce qu\'il me fallait pour ma confiture de tomates ! Merci !',
          reward:{happiness:4, items:{graine_to:3}},
          rewardText:'La confiture de Josette est un délice !' },
        { id:'bucheron2', name:'La Faune de La Carneille',
          desc:'Henri vous recommande de parler à Sylvie la garde forestière.',
          type:'talk', target:'garde',
          locked:true,
          reward:{happiness:3, items:{champignon:3}},
          rewardText:'Sylvie vous accueille chaleureusement, grâce à Henri !' },
        { id:'herboriste2', name:'La Tisane du Pêcheur',
          desc:'Madeleine vous demande de livrer 3 herbes à Robert pour sa tisane spéciale.',
          type:'deliver', target:'pecheur', item:'herbes', qty:3,
          locked:true,
          deliverMsg:'Des herbes de Madeleine ? Sa tisane est légendaire. Merci de jouer les coursiers !',
          reward:{happiness:3, items:{herbes:4, graine_f:2}},
          rewardText:'Robert adore la tisane de Madeleine !' },
        { id:'pecheur2', name:'L\'Esprit Communautaire',
          desc:'Robert croit aux échanges. Faites 5 échanges avec les habitants du village.',
          type:'trade_count', target:5,
          locked:true,
          reward:{happiness:4, items:{poisson:3}},
          rewardText:'Robert est fier de l\'esprit communautaire du village !' },
        { id:'garde2', name:'Le Recensement de Sylvie',
          desc:'Sylvie vous demande d\'observer 5 espèces animales différentes.',
          type:'observe', target:5,
          locked:true,
          reward:{happiness:4, items:{bois:5}},
          rewardText:'Vos notes d\'observation feront le bonheur de Sylvie !' },
        { id:'meunier2', name:'Le Rêve du Meunier',
          desc:'Augustin rêve d\'un moulin pour le village. Construisez-en un !',
          type:'build_type', target:'windmill',
          locked:true,
          reward:{happiness:3, items:{pierre:5}},
          rewardText:'Augustin est aux anges ! Son moulin tourne enfin !' },
        { id:'soeur2', name:'La Soupe de la Chapelle',
          desc:'Sœur Thérèse prépare sa soupe d\'hiver. Apportez-lui 2 citrouilles.',
          type:'deliver', target:'soeur', item:'citrouille', qty:2,
          locked:true,
          deliverMsg:'Des citrouilles ! La soupe d\'hiver sera magnifique. Que Dieu vous bénisse !',
          reward:{happiness:5, items:{pierre:4}},
          rewardText:'La soupe de Sœur Thérèse réchauffe tout le village !' },
        { id:'apiculteur2', name:'L\'Ami des Abeilles',
          desc:'Paul veut que vous deveniez ami avec Josette. Échangez avec elle jusqu\'au niveau 2.',
          type:'friendship', target:'fermiere', level:2,
          locked:true,
          reward:{happiness:3, items:{miel:4}},
          rewardText:'Paul baptise une ruche de votre nom !' },
        // --- Quête finale, toujours en dernier ---
        { id:'fete', name:'La Grande Fête du Village',
          desc:'Rassembler 3 de chaque légume, inviter les habitants, et parler au Maire !',
          type:'fete_finale',
          isFinal: true,
          reward:{},
          rewardText:'FÉLICITATIONS ! La fête bat son plein ! Tout le monde danse !' },
    ],

    // --- Seasons ---
    SEASONS: ['printemps', 'ete', 'automne', 'hiver'],
    SEASON_COLORS: {
        printemps: { grass: '#7EC850', tree: '#4CAF50', sky: '#87CEEB' },
        ete:       { grass: '#5DA832', tree: '#2E7D32', sky: '#64B5F6' },
        automne:   { grass: '#C8A040', tree: '#E65100', sky: '#BCAAA4' },
        hiver:     { grass: '#C8D8C8', tree: '#78909C', sky: '#B0BEC5' },
    },
    TURNS_PER_SEASON: 25,

    FLOWER_COLORS: ['#FF6B8A','#FFB347','#FFE66D','#88DD44','#77CCFF','#CC88FF','#FF88CC','#FFFFFF'],

    // --- Resource spots ---
    RESOURCE_SPOTS: {
        'carneille':    [{rx:-3,ry:2,item:'bois',qty:3},{rx:4,ry:-1,item:'bois',qty:2},{rx:-1,ry:-3,item:'champignon',qty:2}],
        'taillebois':   [{rx:2,ry:-2,item:'bois',qty:3},{rx:-2,ry:3,item:'champignon',qty:2}],
        'tourailles':   [{rx:-3,ry:1,item:'pierre',qty:3},{rx:2,ry:2,item:'pierre',qty:2}],
        'ndrocher':     [{rx:1,ry:-2,item:'pierre',qty:3},{rx:-2,ry:1,item:'pierre',qty:2}],
        'segrie':       [{rx:2,ry:-1,item:'herbes',qty:2},{rx:-2,ry:2,item:'fleur',qty:2}],
        'breel':        [{rx:-3,ry:-1,item:'bois',qty:1},{rx:3,ry:1,item:'graine_p',qty:1}],
        'ronfeugerai':  [{rx:3,ry:0,item:'poisson',qty:2},{rx:-2,ry:2,item:'bois',qty:2}],
        'athis':        [{rx:5,ry:-3,item:'pomme',qty:2}],
    },
};
